#!/bin/sh

ADDR_RULE_PREF=10000
NW_RULE_PREF=20000
LO_RULE_PREF=91000

#this script only applies to static configurations
if [ "$METHOD" != "static" ];
then
    exit 0
fi

#get route
old_rt_table=100

#delete rules, routes etc. are taken care of automatically
ip -4 rule del from ${IF_ADDRESS}${IF_NETMASK:+/$IF_NETMASK} \
    pref ${ADDR_RULE_PREF} lookup ${old_rt_table}
ip -4 rule del from all to ${IF_ADDRESS}${IF_ADDRESS:+/$IF_NETMASK} pref \
    ${NW_RULE_PREF} lookup ${old_rt_table}
ip -4 rule del from all iif lo lookup ${old_rt_table} pref ${LO_RULE_PREF}

exit 0
